// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookFormatSelectController from "./book_format_select_controller.js"
application.register("book-format-select", BookFormatSelectController)

import BurgermenuController from "./burgermenu_controller.js"
application.register("burgermenu", BurgermenuController)

import CoverdropController from "./coverdrop_controller.js"
application.register("coverdrop", CoverdropController)

import GenreSelectController from "./genre_select_controller.js"
application.register("genre-select", GenreSelectController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import NotificationController from "./notification_controller.js"
application.register("notification", NotificationController)

import PublisherSelectController from "./publisher_select_controller.js"
application.register("publisher-select", PublisherSelectController)

import ShelfSelectController from "./shelf_select_controller.js"
application.register("shelf-select", ShelfSelectController)

import SweetalertController from "./sweetalert_controller.js"
application.register("sweetalert", SweetalertController)

import TagSelectController from "./tag_select_controller.js"
application.register("tag-select", TagSelectController)
