// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BarcodeController from "./barcode_controller"
application.register("barcode", BarcodeController)

import BurgermenuController from "./burgermenu_controller"
application.register("burgermenu", BurgermenuController)

import CoverdropController from "./coverdrop_controller"
application.register("coverdrop", CoverdropController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import QuickSearchController from "./quick_search_controller"
application.register("quick-search", QuickSearchController)

import SweetalertController from "./sweetalert_controller"
application.register("sweetalert", SweetalertController)

import TomSelectAddController from "./tom_select_add_controller"
application.register("tom-select-add", TomSelectAddController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
