inherit_from:
  - .rubocop_todo.yml
  - /usr/local/lib/node_modules/@prettier/plugin-ruby/rubocop.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/*"
    - "config/environments/*"
    - "doc/**/*"
    - "lib/**/*"
    - "log/**/*"
    - "mockup"
    - "node_modules/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "spec-old/**/*"
